### ISSUE TITLE
example.py error

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#127]
I am trying to start a local server, but get a socket error. I am using python3.6 and anaconda, neuroglancer is looking for `system_bus_socket` in a wrong place, the file is in `/var/run/dbus`.
```
python2 -i example.py 
>>> [18184:18208:0613/170609.227749:ERROR:bus.cc(427)] Failed to connect to the bus: Failed to connect to socket /usr/people/jingpeng/lib/anaconda3/var/run/dbus/system_bus_socket: No such file or directory
Created new window in existing browser session.
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42940)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/people/jingpeng/workspace/neuroglancer/python/neuroglancer/server.py", line 88, in do_GET
    self.handle_static_request(m.group(1), m.group(2))
  File "/usr/people/jingpeng/workspace/neuroglancer/python/neuroglancer/server.py", line 96, in handle_static_request
    data, content_type = global_static_content_source.get(path)
  File "/usr/people/jingpeng/workspace/neuroglancer/python/neuroglancer/static/__init__.py", line 46, in get
    return self.get_content(name), guess_mime_type_from_path(name)
  File "/usr/people/jingpeng/workspace/neuroglancer/python/neuroglancer/static/__init__.py", line 70, in get_content
    r = requests.get(full_url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /index.html (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f337a5dd1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by jingpengw** [comment]
just tried in my laptop, get another error:
```
python -i example.py 
>>> 127.0.0.1 - - [13/Jun/2017 23:06:31] code 404, message Not Found
127.0.0.1 - - [13/Jun/2017 23:06:31] "GET /static/b'5fdb9b6305a8228e4caed07995dad24d0f34ccca'/ HTTP/1.1" 404 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59846)
Traceback (most recent call last):
  File "/Users/jpwu/libs/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/jpwu/libs/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/Users/jpwu/libs/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by jingpengw** [comment]
just find that this is a duplication of 
https://github.com/seung-lab/neuroglancer/issues/19

**Comment by jingpengw** [comment]
example works again. close.
