### ISSUE TITLE
boto times out when reading/writting from s3

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#46]
```
Traceback (most recent call last):
  File "/neuroglancer/python/neuroglancer/pipeline/task_execution.py", line 24, in <module>
    task.execute()
  File "neuroglancer/pipeline/tasks.py", line 518, in execute
    s3i.apply_gzip_encoding(self.prefix)
  File "neuroglancer/pipeline/storage.py", line 301, in apply_gzip_encoding
    k = k.copy(k.bucket.name, k.name, {'Content-Encoding':'gzip'}, preserve_acl=True)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 500, in copy
    src_version_id=self.version_id)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 873, in copy_key
    body = response.read()
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 630, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)"    
```

**Comment by tartavull** [comment]
```
Traceback (most recent call last):
  File "/neuroglancer/python/neuroglancer/pipeline/task_execution.py", line 24, in <module>
    task.execute()
  File "neuroglancer/pipeline/tasks.py", line 518, in execute
    s3i.apply_gzip_encoding(self.prefix)
  File "neuroglancer/pipeline/storage.py", line 301, in apply_gzip_encoding
    k = k.copy(k.bucket.name, k.name, {'Content-Encoding':'gzip'}, preserve_acl=True)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 500, in copy
    src_version_id=self.version_id)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 873, in copy_key
    body = response.read()
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 642, in _read_chunked
    raise IncompleteRead(''.join(value))
IncompleteRead: IncompleteRead(41 bytes read)"    
```

**Comment by tartavull** [comment]
https://github.com/boto/boto3/issues/185

**Comment by tartavull** [comment]
this is a nice library to use https://pypi.python.org/pypi/retrying
to implement some exponential backoff retry

**Comment by william-silversmith** [comment]
I got a sweet PR into retry's successor: https://github.com/jd/tenacity/pull/70
