### ISSUE TITLE
Downsampling fails with this error

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#55]
```  message: "raised unsupported operand type(s) for &: 'numpy.float64' and 'numpy.float64'
 Traceback (most recent call last):
  File "/neuroglancer/python/neuroglancer/pipeline/task_execution.py", line 12, in <module>
    task.execute()
  File "neuroglancer/pipeline/tasks.py", line 129, in execute
    self._download_input_chunk()
  File "neuroglancer/pipeline/tasks.py", line 174, in _download_input_chunk
    self._downsample_chunk(chunk)
  File "neuroglancer/pipeline/tasks.py", line 180, in _downsample_chunk
    self._data = downsample.downsample_segmentation(chunk, self._downsample_ratio)
  File "neuroglancer/downsample.py", line 135, in downsample_segmentation
    return downsample_segmentation(output, factor)
  File "neuroglancer/downsample.py", line 101, in downsample_segmentation
    is_twod_pot_downsample = np.any(factor == 1) and is_pot(reduce(operator.mul, factor))
  File "neuroglancer/downsample.py", line 100, in <lambda>
    is_pot = lambda x: (x != 0) and not (x & (x - 1)) # is power of two
TypeError: unsupported operand type(s) for &: 'numpy.float64' and 'numpy.float64'

 DownsampleTask(chunk_path='s3://neuroglancer/pinky40_v11/watershed/8_8_40/5120-5632_4352-4864_640-704',layer_path='s3://neuroglancer/pinky40_v11/watershed/')
 on host downsample-deployment-2646365293-95mv2"  
```

**Comment by william-silversmith** [comment]
This happens when you use segmentation downsampling on affinity maps. It
should be using striding
