### ISSUE TITLE
Unknown compression method in a very small percentage of chunks

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#66]
```
  message: "raised Unknown compression method
 Traceback (most recent call last):
  File "/neuroglancer/python/neuroglancer/pipeline/task_execution.py", line 19, in execute
    task.execute()
  File "neuroglancer/pipeline/tasks.py", line 130, in execute
    self._download_input_chunk()
  File "neuroglancer/pipeline/tasks.py", line 174, in _download_input_chunk
    self._input_zmin:self._input_zmax]
  File "neuroglancer/pipeline/precomputed.py", line 79, in __getitem__
    content =  self._storage.get_file(file_path)
  File "neuroglancer/pipeline/storage.py", line 125, in get_file
    content = self._maybe_uncompress(content)
  File "neuroglancer/pipeline/storage.py", line 175, in _maybe_uncompress
    return self._uncompress(content)
  File "neuroglancer/pipeline/storage.py", line 190, in _uncompress
    return gfile.read()
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 200, in _read_gzip_header
    raise IOError, 'Unknown compression method'
IOError: Unknown compression method

 DownsampleTask(chunk_path='gs://neuroglancer/pinky40_v11/mean_0.27_segmentation/8_8_40/11776-12288_11520-12032_832-896',layer_path='gs://neuroglancer/pinky40_v11/mean_0.27_segmentation/')
 on host downsample-deployment-3441195240-jg95c"    
 }
```

**Comment by tartavull** [comment]
oops 
There is once chance in 65536 that a file that is not gzipped will
be ungzipped. That's why is better to set uncompress to False in
get file.
Which happens because of #65

**Comment by tartavull** [comment]
@jonathanzung  This will make yacn crash in 4 chunks
