### ISSUE TITLE
threading error 

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#69]
```
Exception in thread Thread-163:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "neuroglancer/pipeline/storage.py", line 88, in _process_task
    error = e.value
AttributeError: 'NotFound' object has no attribute 'value'
```

**Comment by william-silversmith** [comment]
I think think (as noted in PR #62 ) this error is already fixed in some fashion.
